In [1]:
import numpy as np
import pandas as pd

In [5]:
data = pd.read_csv('D:\Machine Leraning\Advance-Machine-Learning\Dataset\play_tennis.csv')

In [8]:
data.drop("day", axis = 1, inplace = True)

In [9]:
data

     outlook  temp humidity    wind play
0      Sunny   Hot     High    Weak   No
1      Sunny   Hot     High  Strong   No
2   Overcast   Hot     High    Weak  Yes
3       Rain  Mild     High    Weak  Yes
4       Rain  Cool   Normal    Weak  Yes
5       Rain  Cool   Normal  Strong   No
6   Overcast  Cool   Normal  Strong  Yes
7      Sunny  Mild     High    Weak   No
8      Sunny  Cool   Normal    Weak  Yes
9       Rain  Mild   Normal    Weak  Yes
10     Sunny  Mild   Normal  Strong  Yes
11  Overcast  Mild     High  Strong  Yes
12  Overcast   Hot   Normal    Weak  Yes
13      Rain  Mild     High  Strong   No

In [10]:
# Problem 1

# outlook = Sunny, temp = Hot, Humidity = High, Wind = Weak

#Play or Not play?

In [11]:
#Solution:

#P(Yes | Sunny, Hot, High, Weak) = p(Sunny | Yes) * p(Hot | Yes) * p(High | Yes) * p(Weak | Yes) * P(Yes) 
#P(No | Sunny, Hot, High, Weak) = p(Sunny | No) * p(Hot | No) * p(High | No) * p(Weak | No) * P(No)

In [12]:
#p(Yes), p(NO)

In [14]:
data['play'].value_counts()

Yes    9
No     5
Name: play, dtype: int64

In [16]:
pYes = 9/14
pNo = 5/14

In [18]:
pd.crosstab(data['outlook'], data["play"])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [19]:
pOverNo = 0
pRainNo = 2/5
pSunnyNo = 3/5

pOverYes = 4/9
pRainYes = 3/9  
pSunnyYes = 2/9

In [20]:
pd.crosstab(data['temp'], data["play"])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [21]:
pCoolNo = 1/5
pHotNo = 2/5
pMildNo = 2/5

pCoolYes = 3/9
pHotYes = 4/9
pMildYes = 2/9

In [22]:
pd.crosstab(data['humidity'], data["play"])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [23]:
pHighNo = 4/5
pNormNo = 1/5

pHighYes = 3/9
pNormYes = 6/9

In [24]:
pd.crosstab(data['wind'], data["play"])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [25]:
pStrongNo = 3/5
pWeakNo = 2/5

pStrongYes = 3/9
pWeakYes = 6/9

In [26]:
Pyes = pSunnyYes * pHotYes * pHighYes * pWeakYes * pYes

In [28]:
Pyes

0.014109347442680773

In [29]:
Pno = pSunnyNo * pHotNo * pHighNo * pWeakNo * pNo
Pno

0.02742857142857143

In [30]:
#NO Play